/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package teclado_prop;

import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Aitor
 */
public class Presentacion extends javax.swing.JFrame {

    /**
     * Creates new form prueba
     */
    CtrlPresentacion contd = new CtrlPresentacion();
    private String x;
    private String x2;
    private String[] list;
    File abre;
    String mensaje_error = "";
    String[] texto = null;
    Calculo c;
    
    public Presentacion() throws Exception {
        initComponents();
        this.setBounds(0, 0, 650, 600);
        this.setLocationRelativeTo(null);
        contd.inicializar(this);
        list = contd.nombres_Teclados();
        for (int i = 0; i < list.length; i++) {
            predeterminados.addItem(list[i]);
            jComboBox1.addItem(list[i]);
        }
        Font f = new Font( "Courier New",Font.PLAIN,15 );
        jTextArea1.setFont(f);
        jTextArea2.setFont(f);
        jTextArea3.setFont(f);
        teclado.setFont(f);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        predeterminados = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField7 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        filas = new javax.swing.JTextField();
        columnas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        teclado = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        calcular = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tiempo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        swap1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        swap2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        desechar = new javax.swing.JButton();
        swap = new javax.swing.JButton();
        cambiar_nombre = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        warning = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        predeterminados.setToolTipText("Muestra la lista de teclados");
        predeterminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predeterminadosActionPerformed(evt);
            }
        });
        jPanel1.add(predeterminados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));

        jButton1.setText("Mostrar");
        jButton1.setToolTipText("Muestra el teclado seleccionado en el cuadro de texto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jButton4.setText("Eliminar");
        jButton4.setToolTipText("Elimina el teclado seleccionado");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel12.setText("VISUALIZAR TECLADOS");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, 140, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 260, 210));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setToolTipText("Seleccionar el teclado para calcular la nueva distribución");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        jTextField7.setText("url archivo");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, -1));

        jButton5.setText("Abrir");
        jButton5.setToolTipText("Clic aquí para abrir el archivo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 60, 20));

        jTextField9.setText("jTextField9");
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel5.setText("Tiempo de cálculo:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 20));

        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 70, -1));

        jTextField10.setText("jTextField10");
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, 80));

        jLabel14.setText("SELECCIONAR TEXTO");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 150, 20));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 250, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 290, 210));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.setToolTipText("Insertar el nombre del teclado");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel3.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 70, 30));

        filas.setToolTipText("Insertar el número de filas del teclado");
        filas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filasActionPerformed(evt);
            }
        });
        jPanel3.add(filas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 40, 30));

        columnas.setToolTipText("Insertar el número de columnas del teclado");
        columnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnasActionPerformed(evt);
            }
        });
        jPanel3.add(columnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 40, 30));

        jLabel1.setText("Nombre del teclado");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setText("Filas");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel3.setText("Columnas");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel4.setText("Distribución de Teclas");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        aceptar.setText("Aceptar");
        aceptar.setToolTipText("Clic aquí para guardar el teclado");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel3.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        cancelar.setText("Cancelar");
        cancelar.setToolTipText("Clic aquí para desechar el teclado");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel3.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel13.setText("CREAR TECLADO");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 130, -1));

        teclado.setColumns(20);
        teclado.setRows(3);
        teclado.setToolTipText("Insertar aquí la distribución de teclas");
        jScrollPane4.setViewportView(teclado);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 260, 270));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calcular.setText("Calcular");
        calcular.setToolTipText("Clic aquí para calcular la nueva distribución");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        jPanel6.add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel7.setText("Tiempo de cálculo:");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 130, 20));

        tiempo.setEditable(false);
        tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoActionPerformed(evt);
            }
        });
        jPanel6.add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 40, 30));

        jLabel8.setText("Cambiar:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, 20));

        swap1.setToolTipText("Insertar aquí la primera tecla para intercambiar");
        swap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swap1ActionPerformed(evt);
            }
        });
        jPanel6.add(swap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 20, -1));

        jLabel9.setText("por");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, 20));

        swap2.setToolTipText("Insertar aquí la segunda tecla para intercambiar");
        swap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swap2ActionPerformed(evt);
            }
        });
        jPanel6.add(swap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 30, -1));

        jLabel10.setText("Cambiar nombre:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 20));

        nombre2.setToolTipText("Insertar aquí el nuevo nombre para el teclado");
        nombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre2ActionPerformed(evt);
            }
        });
        jPanel6.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 100, -1));

        guardar.setText("Guardar");
        guardar.setToolTipText("Añade el teclado al listado");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel6.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        desechar.setText("Desechar");
        desechar.setToolTipText("Descarta los cambios");
        desechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desecharActionPerformed(evt);
            }
        });
        jPanel6.add(desechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        swap.setText("ok");
        swap.setToolTipText("Clic aquí para confirmar los cambios");
        swap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapActionPerformed(evt);
            }
        });
        jPanel6.add(swap, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        cambiar_nombre.setText("ok");
        cambiar_nombre.setToolTipText("Clic aquí para confirmar los cambios");
        cambiar_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiar_nombreActionPerformed(evt);
            }
        });
        jPanel6.add(cambiar_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 50, -1));

        jLabel15.setText("CALCULAR SOLUCIÓN");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, -1));

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 120));

        jLabel16.setText("miliseg");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 290, 290));

        warning.setEditable(false);
        warning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warningActionPerformed(evt);
            }
        });
        getContentPane().add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 530, 30));

        jLabel11.setText("Warnings:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void predeterminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predeterminadosActionPerformed
        x = (String)predeterminados.getSelectedItem();
        
    }//GEN-LAST:event_predeterminadosActionPerformed

    private void filasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filasActionPerformed

    private void columnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnasActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
            String nom = nombre.getText();
            int n = Integer.parseInt(filas.getText());
            int m = Integer.parseInt(columnas.getText());
            String letras = teclado.getText();
            try {
                contd.anadir_teclado(nom,n,m,letras);
            } catch (Exception ex) {
                mensaje_error = ex.getMessage();
                warning.setText(mensaje_error);
                // Logger.getLogger(CtrlPresentacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            refrescar_combobox();
            vaciar_crear_teclado();
            predeterminados.setSelectedIndex(predeterminados.getItemCount()-1);
            jTextArea1.setText(contd.consultar_teclado(x));
    }//GEN-LAST:event_aceptarActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTextArea2.setText("");
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        abre = file.getSelectedFile();
        URL url = null;
        try {
            url = abre.toURL();
        } catch (MalformedURLException ex) {
            mensaje_error = ex.getMessage();
            warning.setText(mensaje_error);
            Logger.getLogger(CtrlPresentacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        String archivo = url.getPath();
        jTextField7.setText(archivo);
        texto = null;
        try {
            texto = contd.leer_archivo(archivo);
            contd.escribir_archivo(".\\src\\teclado_prop\\STUB4.txt", texto);
        } catch (IOException ex) {
            mensaje_error = ex.getMessage();
            warning.setText(mensaje_error);
            //Logger.getLogger(CtrlPresentacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < texto.length; i++) {
            jTextArea2.setText(jTextArea2.getText()+"\n"+texto[i]);
        }
        
        
 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        c = new Calculo(this);
        try {
           contd.crear_teclado(x2, jTextArea2.getText());
           c.visualizar();
            
        } catch (Exception ex) {
            mensaje_error = ex.getMessage();
            warning.setText(mensaje_error);
            //Logger.getLogger(CtrlPresentacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_calcularActionPerformed

    private void swap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swap2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_swap2ActionPerformed

    private void swap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_swap1ActionPerformed

    private void nombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre2ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        try {
            // TODO add your handling code here:
            contd.anadir_tec_en_creacion();
        } catch (IOException ex) {
            mensaje_error = ex.getMessage();
            warning.setText(mensaje_error);
            Logger.getLogger(Presentacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            mensaje_error = ex.getMessage();
            warning.setText(mensaje_error);
            Logger.getLogger(Presentacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        refrescar_combobox();
        predeterminados.setSelectedIndex(predeterminados.getItemCount()-1);
        jTextArea1.setText(contd.consultar_teclado(x));
        vaciar_crear_teclado2();
    }//GEN-LAST:event_guardarActionPerformed

    private void desecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desecharActionPerformed
        // TODO add your handling code here:
        contd.desechar_tec_en_creacion();
        vaciar_crear_teclado2();
    }//GEN-LAST:event_desecharActionPerformed

    private void cambiar_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiar_nombreActionPerformed
        try {
            // TODO add your handling code here:
            contd.cambiar_nombre(nombre2.getText());
            jTextArea3.setText(contd.consultar_tec_en_creacion());
        } catch (Exception ex) {
            mensaje_error = ex.getMessage();
            warning.setText(mensaje_error);
            //Logger.getLogger(CtrlPresentacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cambiar_nombreActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane jop = new JOptionPane(); 
        if(predeterminados.getItemCount() > 1) {
            if(jop.showConfirmDialog(this, "¿Estas seguro que deseas eliminar el teclado " + x + "?", "ELIMINAR TECLADO", JOptionPane.OK_CANCEL_OPTION) == 0) {
                try {
                    contd.eliminar_teclado(x);
                } catch (IOException ex) {
                    mensaje_error = ex.getMessage();
                    warning.setText(mensaje_error);
                    Logger.getLogger(Presentacion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    mensaje_error = ex.getMessage();
                    warning.setText(mensaje_error);
                    Logger.getLogger(Presentacion.class.getName()).log(Level.SEVERE, null, ex);
                }
                refrescar_combobox();
                jTextArea1.setText(contd.consultar_teclado(x));
            } 
        }
        else {
            jop.showMessageDialog(this, "Tiene que haber al menos un teclado", "ERROR", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(contd.consultar_teclado(x));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        vaciar_crear_teclado();
    }//GEN-LAST:event_cancelarActionPerformed

    private void warningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warningActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        x2 = (String)jComboBox1.getSelectedItem();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void swapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swapActionPerformed
        try {
            contd.swap_teclas(swap1.getText(),swap2.getText());
            jTextArea3.setText(contd.consultar_tec_en_creacion());
        } catch (Exception ex) {
            mensaje_error = ex.getMessage();
            warning.setText(mensaje_error);
            
            //Logger.getLogger(CtrlPresentacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_swapActionPerformed

    private void refrescar_combobox() {
        predeterminados.removeAllItems();
        jComboBox1.removeAllItems();
        list = contd.nombres_Teclados();
        for (int i = 0; i < list.length; i++) {
            predeterminados.addItem(list[i]);
            jComboBox1.addItem(list[i]);
        }
    }
    
    private void vaciar_crear_teclado() {
        nombre.setText("");
        filas.setText("");
        columnas.setText("");
        teclado.setText("");
    }
    
    private void vaciar_crear_teclado2() {
        tiempo.setText("");
        swap1.setText("");
        swap2.setText("");
        nombre2.setText("");
        jTextArea3.setText("");
        jTextArea2.setText("");
        jTextField7.setText("url archivo");
    }
    
    public void esconder() {
        this.setVisible(false);
    }
    
    public void visualizar() {
        this.setVisible(true);
    }
    
    public void finalitzar_calcul() {
        this.contd.finalitzar_calcul();
    }
    
    public void calcul_realitzat(long temps) {
        try {
            this.contd.sol_cor();
             jTextArea3.setText(contd.consultar_tec_en_creacion());
        tiempo.setText(Long.toString(temps));
        }
        catch (Exception ex) {
            mensaje_error = ex.getMessage();
            warning.setText(mensaje_error);
            //Logger.getLogger(Presentacion.class.getName()).log(Level.SEVERE, null, ex);
                }
        
         c.esconder();
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Presentacion().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Presentacion.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton calcular;
    private javax.swing.JButton cambiar_nombre;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField columnas;
    private javax.swing.JButton desechar;
    private javax.swing.JTextField filas;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombre2;
    private javax.swing.JComboBox predeterminados;
    private javax.swing.JButton swap;
    private javax.swing.JTextField swap1;
    private javax.swing.JTextField swap2;
    private javax.swing.JTextArea teclado;
    private javax.swing.JTextField tiempo;
    private javax.swing.JTextField warning;
    // End of variables declaration//GEN-END:variables
}
